app/models/AuthItem.php
<?php

namespace app\models;

use app\components\mytraits\LogTrait;
use Yii;

/**
 * This is the model class for table "auth_item".
 *
 * @property string $name
 * @property integer $type
 * @property string $description
 * @property string $rule_name
 * @property string $data
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property AuthAssignment[] $authAssignments
 * @property AuthRule $ruleName
 * @property AuthItemChild[] $authItemChildren
 * @property AuthItemChild[] $authItemChildren0
 */
class AuthItem extends \yii\db\ActiveRecord
{
    //加载日志钩子
    use LogTrait;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'auth_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'type','description'], 'required'],
            [['type', 'created_at', 'updated_at'], 'integer'],
            [['description', 'data'], 'string'],
            [['name', 'rule_name'], 'string', 'max' => 64]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => 'KEY',
            'type' => 'Type',
            'description' => '名称描述',
            'rule_name' => 'Rule Name',
            'data' => 'Data',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthAssignments()
    {
        return $this->hasMany(AuthAssignment::className(), ['item_name' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRuleName()
    {
        return $this->hasOne(AuthRule::className(), ['name' => 'rule_name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItemChildren()
    {
        return $this->hasMany(AuthItemChild::className(), ['parent' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItemChildren0()
    {
        return $this->hasMany(AuthItemChild::className(), ['child' => 'name']);
    }


    public function getTopmenu()
    {
        return $this->hasOne(AuthMenu::className(), ['id' => 'menu_id'])
            ->viaTable('auth_menu_item',['item_name' => 'name' ]);

    }
}

app/views/rabc/rcreate.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:38
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\components\widgets\FileuploadWidget;
$this->params['breadcrumbs'][] = ['label' => '角色管理', 'url' => ['rlist'] ];
$this->params['breadcrumbs'][] =  $model->isNewRecord ? '新增角色' : '编辑角色';



?>



<?php if($model->isNewRecord): ?>
    <?php $form = ActiveForm::begin(['action' => ['rabc/rcreate'],'method'=>'post', 'options' => ['enctype' => 'multipart/form-data']]); ?>
<?php else: ?>
    <?php $form = ActiveForm::begin(['action' => ['rabc/redit'],'method'=>'post','options' => ['enctype' => 'multipart/form-data']]); ?>
<?php endif; ?>

<div class="row">
    <div class="col-xs-12">
        <section class="panel">
            <div class="panel-body">
                <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($model, 'description')->textInput(['maxlength' => 255]) ?>

                <div class="form-group">
                    <header class="panel-heading">资源列表</header>
                    <?php echo  $this->render('_widgets/_tree'); ?>
                    <header class="panel-heading"></header>
                </div>


                <div class="form-group">
                    <?=Html::hiddenInput('AuthItem[type]',1); ?>
                    <?=Html::hiddenInput('res_str',empty($res_str) ? "":$res_str); ?>
                    <?php if(!$model->isNewRecord): ?>
                        <?=Html::hiddenInput('name',$model['name']); ?>
                    <?php endif; ?>
                    <?= Html::submitButton("<i class='icon-ok bigger-110'></i>保存", ['class'=>'btn btn-primary','name' =>'submit-button']) ?>
                    &nbsp;
                    <?= Html::resetButton("<i class='icon-undo bigger-110'></i>重置", ['class'=>'btn  btn-primary','name' =>'submit-button']) ?>
                </div>


            </div>
        </section>
    </div>



</div>
<?php ActiveForm::end(); ?>

</div>

app/views/rabc/res_create.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:38
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\components\widgets\FileuploadWidget;

$this->params['breadcrumbs'][] = ['label' => '资源', 'url' => ['reslist']];
$this->params['breadcrumbs'][] = $model->isNewRecord ? '新增资源' : '编辑资源';


?>

<?php if ($model->isNewRecord): ?>
    <?php $form = ActiveForm::begin(['action' => ['rabc/rescreate'], 'method' => 'post', 'options' => ['enctype' => 'multipart/form-data']]); ?>
<?php else: ?>
    <?php $form = ActiveForm::begin(['action' => ['rabc/resedit'], 'method' => 'post', 'options' => ['enctype' => 'multipart/form-data']]); ?>
<?php endif; ?>

<div class="row">
    <div class="col-xs-12">
        <section class="panel">
            <div class="panel-body">
                <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>

                <?= $form->field($model, 'description')->textInput(['maxlength' => 255]) ?>

                <div class="form-group ">
                    <?php echo Html::DropDownList('menu_id', empty($menuModel) ? 0 : $menuModel['menu_id'], \app\models\AuthMenu::getMenus(), ['prompt' => '--请选择所属菜单--', 'class' => 'form-control m-bot15']); ?>
                </div>
                <div class="form-group">
                    <?= Html::hiddenInput('AuthItem[type]', 2); ?>
                    <?php if (!$model->isNewRecord): ?>
                        <?= Html::hiddenInput('name', $model['name']); ?>
                    <?php endif; ?>
                    <?= Html::submitButton("<i class='icon-ok bigger-110'></i>保存", ['class' => 'btn btn-primary', 'name' => 'submit-button']) ?>
                    &nbsp;
                    <?= Html::resetButton("<i class='icon-undo bigger-110'></i>重置", ['class' => 'btn  btn-primary', 'name' => 'submit-button']) ?>
                </div>


            </div>
        </section>
    </div>


</div>
<?php ActiveForm::end(); ?>


<?php if (!$model->isNewRecord): ?>
    <div class="row">

        <div class="col-md-12">
            <div class="panel">
                <header class="panel-heading">
                    操作日志
                            <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                             </span>
                </header>
                <div class="panel-body">
                    <ul class="goal-progress">
                        <?php if (!empty($logs)): ?>
                            <?php foreach ($logs as $log): ?>
                                <li style="padding-bottom: 0;margin-bottom: 0;">
                                    <div class="prog-avatar">
                                        <span class="label label-default"><?= $log['username']; ?></span><br/>
<span class="label label-success">
    <?php if ($log['action'] == 0): ?>添加<?php endif; ?>
    <?php if ($log['action'] == 1): ?>修改<?php endif; ?>
</span>

                                    </div>
                                    <div class="details">
                                        <div class="highlight">
                                            <pre><code class="html"><?= $log['odata']; ?></code></pre>
                                        </div>
                                    </div>
                                </li>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                    <div class="text-center"><a href="#">查看全部(未开发)</a></div>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>

app/views/rabc/reslist.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:15
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->params['breadcrumbs'][] = ['label' => '资源管理', 'url' => ['ulist'] ];
$this->params['breadcrumbs'][] = "资源列表";
?>
<?php $form = ActiveForm::begin(['action' => ['rabc/ulist'],'method'=>'get',]); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <a class="btn btn-primary" href="<?= Yii::$app->urlManager->createUrl(['rabc/rescreate']) ?>" role="button">添加资源</a>
        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>

<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                数据列表
                <span class="tools pull-right">
                            <a href="javascript:;" class="fa fa-chevron-down"></a>
                         </span>
            </header>
            <div class="panel-body">
                <table class="table  table-hover ">
                    <thead>
                    <tr>
                        <th><?=$attrbutes['name']; ?></th>
                        <th><?=$attrbutes['description']; ?></th>
                        <th>
                            所属模块
                        </th>
                        <th>操 作</th>

                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach($list as $key => $item): ?>
                        <tr>

                            <td>
                                <?=Html::encode(empty($item['name']) ? "—":$item['name']); ?>

                            </td>
                            <td ><?=Html::encode(empty($item['description']) ? "—":$item['description']); ?></td>
                            <td>
                                <span class="label label-default"><?= empty($item->topmenu) ? "": $item->topmenu['name']; ?></span>
                            </td>

                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a class="btn btn-default" type="button" href="<?=Yii::$app->urlManager->createUrl(['rabc/resedit','name' => $item['name']]); ?>">编辑</a>
                                    <a class="btn btn-danger delcve" type="button" data-name="<?=$item['name'];?>">删除</a>

                                </div>


                            </td>
                        </tr>
                    <?php endforeach; ?>



                    </tbody>
                </table>
                <div class="row">
                    <div class="col-lg-6"><div class="dataTables_info" id="editable-sample_info">
                            显示记录 <?= $pages->offset+1; ?> 到 <?= $pages->offset+$pages->limit; ?>,共 <?= $pages->totalCount; ?> 条记录
                        </div></div>
                    <div class="col-lg-6">
                        <div class="dataTables_paginate paging_bootstrap pagination">
                            <?=  \yii\widgets\LinkPager::widget([
                                'pagination' => $pages,
                                'lastPageLabel' => "最后一页",
                                'firstPageLabel' => "第一页",
//                            'linkOptions' =>'ss'

                            ]); ?>

                        </div></div></div>
            </div>
        </section>
    </div>
</div>







<!--删除crumb-->




<script type="text/javascript">

    $('.delcve').on('click', function(){

        var name = $(this).data("name");
        layer.msg('确定删除吗?', {
            time: 0 //不自动关闭
            ,btn: ['确定', '取消']
            ,yes: function(index){
                layer.close(index);
                window.location.href = "<?=Yii::$app->urlManager->createUrl(['rabc/resdel']); ?>&name="+name;
            }
        });


    });

</script>

app/views/rabc/rlist.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:15
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->params['breadcrumbs'][] = ['label' => '角色管理', 'url' => ['ulist'] ];
$this->params['breadcrumbs'][] = "角色列表";
?>
<?php $form = ActiveForm::begin(['action' => ['rabc/ulist'],'method'=>'get',]); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <a class="btn btn-primary" href="<?= Yii::$app->urlManager->createUrl(['rabc/rcreate']) ?>" role="button">添加角色</a>
        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>

<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                数据列表
                <span class="tools pull-right">
                            <a href="javascript:;" class="fa fa-chevron-down"></a>
                         </span>
            </header>
            <div class="panel-body">
                <table class="table  table-hover ">
                    <thead>
                    <tr>
                        <th><?=$attrbutes['name']; ?></th>
                        <th><?=$attrbutes['description']; ?></th>
                        <th>操 作</th>

                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach($list as $key => $item): ?>
                        <tr>

                            <td>
                                <?=Html::encode(empty($item['name']) ? "—":$item['name']); ?>

                            </td>
                            <td ><?=Html::encode(empty($item['description']) ? "—":$item['description']); ?></td>


                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a class="btn btn-default" type="button" href="<?=Yii::$app->urlManager->createUrl(['rabc/redit','name' => $item['name']]); ?>">编辑</a>
                                    <a class="btn btn-danger delcve" type="button" data-name="<?=$item['name'];?>">删除</a>

                                </div>


                            </td>
                        </tr>
                    <?php endforeach; ?>



                    </tbody>
                </table>
                <div class="row">
                    <div class="col-lg-6"><div class="dataTables_info" id="editable-sample_info">
                            显示记录 <?= $pages->offset+1; ?> 到 <?= $pages->offset+$pages->limit; ?>,共 <?= $pages->totalCount; ?> 条记录
                        </div></div>
                    <div class="col-lg-6">
                        <div class="dataTables_paginate paging_bootstrap pagination">
                            <?=  \yii\widgets\LinkPager::widget([
                                'pagination' => $pages,
                                'lastPageLabel' => "最后一页",
                                'firstPageLabel' => "第一页",
//                            'linkOptions' =>'ss'

                            ]); ?>

                        </div></div></div>
            </div>
        </section>
    </div>
</div>







<!--删除crumb-->




<script type="text/javascript">

    $('.delcve').on('click', function(){

        var name = $(this).data("name");
        layer.msg('确定删除吗?', {
            time: 0 //不自动关闭
            ,btn: ['确定', '取消']
            ,yes: function(index){
                layer.close(index);
                window.location.href = "<?=Yii::$app->urlManager->createUrl(['rabc/rdel']); ?>&name="+name;
            }
        });


    });

</script>

app/views/rabc/ucreate.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:38
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\components\widgets\EditorWidget;
use app\components\widgets\FileuploadWidget;
use app\components\widgets\ImguploadWidget;
$this->params['breadcrumbs'][] = ['label' => '用户管理', 'url' => ['ulist'] ];
$this->params['breadcrumbs'][] =  $userModel->isNewRecord ? '添加用户' : '编辑用户';

?>
<?php if($userModel->isNewRecord): ?>
    <?php $form = ActiveForm::begin(['action' => ['rabc/ucreate'],'method'=>'post', 'options' => ['enctype' => 'multipart/form-data']]); ?>
<?php else: ?>
    <?php $form = ActiveForm::begin(['action' => ['rabc/uedit'],'method'=>'post','options' => ['enctype' => 'multipart/form-data']]); ?>
<?php endif; ?>

<div class="row">
    <div class="col-xs-12">
        <section class="panel">
            <div class="panel-body">
                <?= $form->field($userModel, 'username')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($userModel, 'nickname')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($userModel, 'password')->passwordInput(['maxlength' => 255]) ?>
                <?= $form->field($userModel, 'email')->textInput(['maxlength' => 255]) ?>

                <div class="form-group">
                    <?=Html::label("所属角色");?>
                    <?= Html::checkboxList('roles', empty($roleNames)? []:$roleNames, \yii\helpers\ArrayHelper::map($roleModels, 'name', 'description')) ?>
                </div>


                <div class="form-group">
                    <?php if(!$userModel->isNewRecord): ?>
                        <?=Html::hiddenInput('id',$userModel['id']); ?>
                    <?php endif; ?>
                    <?= Html::submitButton("<i class='icon-ok bigger-110'></i>保存", ['class'=>'btn btn-primary','name' =>'submit-button']) ?>
                    &nbsp;
                    <?= Html::resetButton("<i class='icon-undo bigger-110'></i>重置", ['class'=>'btn  btn-primary','name' =>'submit-button']) ?>
                </div>


            </div>
        </section>
    </div>



</div>
<?php ActiveForm::end(); ?>





<?php if (!$userModel->isNewRecord): ?>
    <div class="row">

        <div class="col-md-12">
            <div class="panel">
                <header class="panel-heading">
                    操作日志
                            <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                             </span>
                </header>
                <div class="panel-body">
                    <ul class="goal-progress">
                        <?php if (!empty($logs)): ?>
                            <?php foreach ($logs as $log): ?>
                                <li style="padding-bottom: 0;margin-bottom: 0;">
                                    <div class="prog-avatar">
                                        <span class="label label-default"><?= $log['username']; ?></span><br/>
<span class="label label-success">
    <?php if ($log['action'] == 0): ?>添加<?php endif; ?>
    <?php if ($log['action'] == 1): ?>修改<?php endif; ?>
</span>

                                    </div>
                                    <div class="details">
                                        <div class="highlight">
                                            <pre><code class="html"><?= $log['odata']; ?></code></pre>
                                        </div>
                                    </div>
                                </li>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                    <div class="text-center"><a href="#">查看全部(未开发)</a></div>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>

app/views/rabc/ulist.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:15
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->params['breadcrumbs'][] = ['label' => '用户管理', 'url' => ['ulist'] ];
$this->params['breadcrumbs'][] = "用户列表";
?>
<?php $form = ActiveForm::begin(['action' => ['rabc/ulist'],'method'=>'get',]); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <a class="btn btn-primary" href="<?= Yii::$app->urlManager->createUrl(['rabc/ucreate']) ?>" role="button">添加用户</a>
        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>

<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                数据列表
                <span class="tools pull-right">
                            <a href="javascript:;" class="fa fa-chevron-down"></a>
                         </span>
            </header>
            <div class="panel-body">
                <table class="table  table-hover ">
                    <thead>
                    <tr>
                        <th><?=$attrbutes['id']; ?></th>
                        <th><?=$attrbutes['username']; ?></th>
                        <th><?=$attrbutes['nickname']; ?></th>
                        <th><?=$attrbutes['email']; ?></th>
                        <th>所属角色</th>
                        <th>状态</th>
                        <th>操 作</th>

                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach($list as $key => $item): ?>
                        <tr>
                            <td>
                                <?=Html::encode($item['id']); ?>
                            </td>

                            <td>
                                <?=Html::encode(empty($item['username']) ? "—":$item['username']); ?>

                            </td>
                            <td>
                                <?=Html::encode(empty($item['nickname']) ? "—":$item['nickname']); ?>
                            </td>


                            <td >
                                <?=Html::encode(empty($item['email']) ? "—":$item['email']); ?>
                            </td>
                            <td >
                                <?php if($item->assignments): ?>

                                    <?php foreach($item->assignments as $assignment ): ?>
                                        <span class="label label-sm label-default"><?=$assignment['description']; ?></span>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </td>
                            <td >

                                <?php echo $item->status == \app\models\User::STATUS_DELETED ? "<span class='label label-sm label-danger'>禁用</span>":"<span class='label label-sm label-success'>正常</span>"; ?>
                            </td>
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a class="btn btn-default" type="button" href="<?=Yii::$app->urlManager->createUrl(['rabc/uedit','id' => $item['id']]); ?>">编辑</a>
                                    <a class="btn btn-danger delcve" type="button" data-id="<?=$item['id'];?>">删除</a>
                                </div>


                            </td>
                        </tr>
                    <?php endforeach; ?>



                    </tbody>
                </table>
                <div class="row">
                    <div class="col-lg-6"><div class="dataTables_info" id="editable-sample_info">
                            显示记录 <?= $pages->offset+1; ?> 到 <?= $pages->offset+$pages->limit; ?>,共 <?= $pages->totalCount; ?> 条记录
                        </div></div>
                    <div class="col-lg-6">
                        <div class="dataTables_paginate paging_bootstrap pagination">
                            <?=  \yii\widgets\LinkPager::widget([
                                'pagination' => $pages,
                                'lastPageLabel' => "最后一页",
                                'firstPageLabel' => "第一页",
//                            'linkOptions' =>'ss'

                            ]); ?>

                        </div></div></div>
            </div>
        </section>
    </div>
</div>







<!--删除crumb-->




<script type="text/javascript">

    $('.delcve').on('click', function(){

        var id = $(this).data("id");
        layer.msg('确定删除吗?', {
            time: 0 //不自动关闭
            ,btn: ['确定', '取消']
            ,yes: function(index){
                layer.close(index);
                window.location.href = "<?=Yii::$app->urlManager->createUrl(['rabc/udel']); ?>&id="+id;
            }
        });


    });

</script>

app/views/rabc/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update User: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>