app/controllers/FileController.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: jiong
 * Date: 2015/12/08
 * Time: 下午3:09
 *   文件上传类
 */
namespace app\controllers;

use app\components\XwcController;
use Yii;

class FileController extends XwcController{
    private $fileType = 0; #0表示文件 1表示图片
    private $fileRoot;
    private $imgRoot;
    private $error;


    // 允许上传的文件后缀
    private  $allowExts = array("gz","zip","rar","tar.gz","jpg","png");
    private  $allowImgExts = array("jpg","png");
    // 允许上传的文件大小
    private  $maxSize =  100*1024;


    public function init(){
        parent::init();
        $this->fileRoot =  $this->imgRoot = Yii::$app->params['file_upload_path'];
//        $this->imgRoot = Yii::$app->basePath.'/uploads/img//';
//        $this->enableCsrfValidation = false;

    }


    /**
     * 上传
     * @param $cat 标识符
     * @param int $type 0表示文件 1表示图片
     */
    public function actionUpload($cat,$type = 0){
        if($type ==0) $this->uploadFile($cat);
        if($type ==1) $this->uploadImg($cat);

    }



    /**
     * 上传文件
     * @param $type
     */
    private function uploadFile($type){

//        $verifyToken = md5('unique_key' . $_POST['timestamp']);#防止恶意提交
//        if (empty($_FILES) || $_POST['token'] == $verifyToken) {
//            $this->error  =  '验证不通过';
//            echo '{"success":false,"msg":"'.$this->error.'"}';
//            exit();
//        }

        $prefixDir = $type.date('/Ym/d/');

        if(!is_writeable($this->fileRoot)) {
            $this->error  =  '上传目录'.$this->fileRoot.'不可写';
            echo '{"status":false,"msg":"'.$this->error.'"}';
            exit();
        }


        if(!is_dir($this->fileRoot.$prefixDir) || !file_exists( $this->fileRoot.$prefixDir)){
            mkdir( $this->fileRoot.$prefixDir,0770,true);
        }


        $file = array_shift($_FILES);
        //相关检查
        if(false == ($this->check($file))){
            $ret['status'] = false;
            $ret['msg'] = $this->error;
        }else{
            $ext = $this->getExt($file['name']);
            $filename = $this->_getFileName($ext);
            $filePath = $this->fileRoot.$prefixDir.$filename;

            if(false == (@move_uploaded_file($file['tmp_name'],$filePath))){
                $ret['status'] = false;
                $ret['msg'] = $filePath;
            }else{
                $ret['status'] = true;
                $ret['msg'] = "ok";
                #文件展示名称
                $ret['fileName'] = $prefixDir.$filename;
                #文件href地址
                $ret['filePath'] = Yii::$app->params['file_show_url'].$prefixDir.$filename;;
            }

        }

        echo json_encode($ret);
        exit;
    }



    /**
     * 上传图片
     *
     * @return string
     */
    private function uploadImg($type){

        $prefixDir = $type.date('/Ym/d/');
        $this->fileType=1;

        if(!is_dir($this->imgRoot.$prefixDir) || !file_exists( $this->imgRoot.$prefixDir)){
            mkdir( $this->imgRoot.$prefixDir,0770,true);
        }


        $file = array_shift($_FILES);
        //相关检查
        if(false == ($this->check($file))){
            $ret['success'] = false;
            $ret['msg'] = $this->error;
        }else{
            $ext = $this->getExt($file['name']);
            $imgName = $this->_getFileName($ext);
            $imgPath = $this->fileRoot.$prefixDir.$imgName;



            if(false == (@move_uploaded_file($file['tmp_name'],$imgPath))){
                $ret['success'] = false;
                $ret['msg'] = '上传文件失败';
            }else{
                $ret['success'] = true;
                #文件href地址
                $ret['file_path'] = Yii::$app->params['file_show_url'].$prefixDir.$imgName;
            }
        }
        echo  json_encode($ret);exit;
    }


    /**
     * 检查上传的文件大小和文件类型
     */
    private function check($file) {
        if($file['error']!== 0) {
            //文件上传失败
            //捕获错误代码
            $this->error = $this->getError($file['error']);
            return false;
        }
        //文件上传成功，进行自定义规则检查
        //检查文件大小
        if(!$this->checkSize($file['size'])) {
            $this->error = '上传文件过大';
            return false;
        }

        //检查文件Mime类型
//        if(!$this->checkType($file['type'])) {
//            $this->error = '上传文件MIME类型不允许！';
//            return false;
//        }
        //检查文件类型
        $ext = $this->getExt($file['name']);
        if(!$this->checkExt($ext)) {
            $this->error ='上传文件类型不允许'.$ext;
            return false;
        }

        //检查是否合法上传
//        if(!$this->checkUpload($file['tmp_name'])) {
//            $this->error = '非法上传文件！';
//            return false;
//        }
        return true;
    }

    /**
     * 生成随机文件名
     *
     * @param $ext
     * @return string
     */
    private function _getFileName($ext){
        return md5(uniqid(rand())).".{$ext}";
    }



    /**
     * 取得文件的后缀
     */
    private function getExt($filename)
    {

        #如果是tar包
        if(strpos($filename,'tar.gz') != false){
            return "tar.gz";
        }

        $pathinfo = pathinfo($filename);
        return strtolower($pathinfo['extension']);
    }


    /**
     * 检查上传的文件后缀是否合法
     */
    private function checkExt($ext)
    {
        if($this->fileType ==1){
            return in_array(strtolower($ext),$this->allowImgExts,true);
        }else{
            return in_array(strtolower($ext),$this->allowExts,true);
        }

        return true;
    }


    /**
     * 检查文件大小是否合法
     */
    private function checkSize($size)
    {
        return !($size > $this->maxSize) || (-1 == $this->maxSize);
    }


}

app/views/article/add.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:38
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\components\widgets\EditorWidget;
use app\components\widgets\FileuploadWidget;
use app\components\widgets\ImguploadWidget;
$this->params['breadcrumbs'][] = ['label' => '文章管理', 'url' => ['plist'] ];
$this->params['breadcrumbs'][] =  $projectModel->isNewRecord ? '新增文章' : '编辑文章';

?>
<?php if($projectModel->isNewRecord): ?>
    <?php $form = ActiveForm::begin(['action' => ['article/create'],'method'=>'post', 'options' => ['enctype' => 'multipart/form-data']]); ?>
<?php else: ?>
    <?php $form = ActiveForm::begin(['action' => ['article/edit'],'method'=>'post','options' => ['enctype' => 'multipart/form-data']]); ?>
<?php endif; ?>
<div class="row">
    <div class="col-xs-9 col-sm-9">
        <section class="panel">
            <div class="panel-body">
                <?= $form->field($projectModel, 'tag')->textInput(['maxlength' => 255,'placeholder' => '多个标签用","分隔']) ?>
                <?= $form->field($projectModel, 'description')->textarea() ?>
                <div class="form-group">
                    <?= EditorWidget::widget([
                        'name' => 'ClArticle[content]',
                        'imgPostUrl' => Yii::$app->urlManager->createUrl(['file/upload', 'cat' => 'editor','type' => 1]),
                        'content' => empty($projectModel['content'])? '' :$projectModel['content'] ]); ?>
                </div>




            </div>
        </section>
    </div>


    <div class="col-xs-2 col-sm-2">
        <section class="panel">
            <div class="panel-body">
                <?= $form->field($projectModel, 'title')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($projectModel, 'author')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($projectModel, 'pub_time')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($projectModel, 'source')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($projectModel, 'url')->textInput(['maxlength' => 255]) ?>


                <div class="form-group">
                    <?= ImguploadWidget::widget([
                        'title' =>'列表页缩略图',
                        'name'=>"ClArticle[thumb]",
                        "value" => $projectModel->isNewRecord ? null : $projectModel['thumb'],
                        'postUrl'=> Yii::$app->urlManager->createUrl(['file/upload', 'cat' => 'thumb'])
                    ]) ?>
                </div>
                <div class="form-group">
                    <?= ImguploadWidget::widget([
                        'title' =>'详情页焦点图',
                        'name'=>"ClArticle[focus]",
                        "value" => $projectModel->isNewRecord ? null : $projectModel['focus'],
                        'postUrl'=> Yii::$app->urlManager->createUrl(['file/upload', 'cat' => 'thumb'])
                    ]) ?>
                </div>

                <div class="form-group">
                    <?php if(!$projectModel->isNewRecord): ?>
                        <?=Html::hiddenInput('id',$projectModel['id']); ?>
                    <?php endif; ?>
                    <?= Html::submitButton("<i class='icon-ok bigger-110'></i>保存", ['class'=>'btn btn-primary','name' =>'submit-button']) ?>
                    &nbsp;
                    <?= Html::resetButton("<i class='icon-undo bigger-110'></i>重置", ['class'=>'btn btn-primary','name' =>'submit-button']) ?>
                </div>


            </div>
        </section>
    </div>

</div>
<?php ActiveForm::end(); ?>

</div>

app/views/article/list.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:15
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->params['breadcrumbs'][] = ['label' => '文章管理', 'url' => ['list'] ];
$this->params['breadcrumbs'][] = "文章列表";
?>
<?php $form = ActiveForm::begin(['action' => ['article/list'],'method'=>'get',]); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <?= Html::submitButton(' 搜 索', ['class'=>'btn btn-primary','name' =>'submit-button']) ?>
            <a class="btn btn-primary" href="<?= Yii::$app->urlManager->createUrl(['article/create']) ?>" role="button">添加文章</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-1">
        <div class="form-group">
            <input name="search[title]" type="text" value="<?=$searchParams['title'] ?>" placeholder=" 标题..." />
        </div>
    </div>


</div>

<?php ActiveForm::end(); ?>

<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                数据列表
                <span class="tools pull-right">
                            <a href="javascript:;" class="fa fa-chevron-down"></a>
                         </span>
            </header>
            <div class="panel-body">
                <table class="table  table-hover ">
                    <thead>
                    <tr>
                        <th><?=$attrbutes['id']; ?></th>
                        <th><?=$attrbutes['title']; ?></th>
                        <th><?=$attrbutes['source']; ?></th>
                        <th><?=$attrbutes['create_time']; ?></th>
                        <th>操 作</th>

                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach($list as $key => $item): ?>
                        <tr>
                            <td>
                                <?=Html::encode($item['id']); ?>
                            </td>

                            <td>
                                <?=Html::encode($item['title']); ?>

                            </td>
                            <td>
                                <?=Html::encode($item['source']); ?>

                            </td>


                            <td >
                                <?=date('Y/m/d H:i:s',$item['create_time']); ?>
                            </td>
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a class="btn btn-default" type="button" href="<?=Yii::$app->urlManager->createUrl(['article/edit','id' => $item['id']]); ?>">编辑</a>
                                    <a class="btn btn-danger delcve" type="button" data-id="<?=$item['id'];?>">删除</a>
                                </div>


                            </td>
                        </tr>
                    <?php endforeach; ?>



                    </tbody>
                </table>
                <div class="row">
                    <div class="col-lg-6"><div class="dataTables_info" id="editable-sample_info">
                            显示记录 <?= $pages->offset+1; ?> 到 <?= $pages->offset+$pages->limit; ?>,共 <?= $pages->totalCount; ?> 条记录
                        </div></div>
                    <div class="col-lg-6">
                        <div class="dataTables_paginate paging_bootstrap pagination">
                            <?=  \yii\widgets\LinkPager::widget([
                                'pagination' => $pages,
                                'lastPageLabel' => "最后一页",
                                'firstPageLabel' => "第一页",
//                            'linkOptions' =>'ss'

                            ]); ?>

                        </div></div></div>
            </div>
        </section>
    </div>
</div>







    <!--删除crumb-->




<script type="text/javascript">

    $('.delcve').on('click', function(){

        var id = $(this).data("id");
        layer.msg('确定删除吗?', {
            time: 0 //不自动关闭
            ,btn: ['确定', '取消']
            ,yes: function(index){
                layer.close(index);
                window.location.href = "<?=Yii::$app->urlManager->createUrl(['article/del']); ?>&id="+id;
            }
        });


    });

</script>