app/models/User.php
<?php
namespace app\models;

use app\components\mytraits\LogTrait;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class User extends ActiveRecord implements IdentityInterface
{
    use LogTrait;

    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dy_user';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => "用户名",
            'password' => '密码',
            'nickname' => '昵称',
            'email' => '邮箱',
            'created_at' => '创建时间',
            'updated_at' => '最后登录时间',
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'email', 'password', 'nickname'], 'required', 'on' => ['create']],
            [['username', 'email', 'nickname'], 'required', 'on' => ['update']],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int)end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->scenario == 'create') {
                $this->setPassword($this->password);
            } else {
                if (empty($this->password)) {
                    unset($this->password);
                } else {
                    $this->setPassword($this->password);
                }
            }
            if ($insert) {
                $this->created_at = time();
                $this->generateAuthKey();
            }
            return true;
        } else {
            return false;
        }
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssignments()
    {

        return $this->hasMany(AuthItem::className(), ['name' => 'item_name'])
            ->viaTable('auth_assignment', ['user_id' => 'id']);

//        return $this->hasMany(AuthAssignment::className(), ['user_id' => 'id']);
    }

    public function getRolenames()
    {
        $roleNames = "";
        foreach ($this->assignments as $role) {
            $roleNames .= $role->description." ";
        }
        return $roleNames;
    }

}

app/views/layouts/_breadcrumbs.php
<?php
/**
 * 面包屑.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 16:50
 */
use yii\widgets\Breadcrumbs;
?>

<div class="row">
    <div class="col-lg-12">
        <!--breadcrumbs start -->
        <?=
        Breadcrumbs::widget(
            [
                'tag' => "ul",
                'homeLink' =>[
                    'label' => 'Home',
                    'encode' =>false,
                    'url' =>'/index.php',
                    'title' => '返回首页',
                    'template'=> '<li><a href="/"><i class="fa fa-home"></i> Home</a></li>'
                ],
                'options' => ['class' => 'breadcrumb panel'],
                'class' => "breadcrumb panel",
                'itemTemplate' =>"<li>{link}</li>",
                'activeItemTemplate' => "<li class=\"active\">{link}</li>",
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
        <!--breadcrumbs end -->
    </div>
</div>

app/views/layouts/main.php
<?php
/**
 * Created by PhpStorm.
 * User: gaojiyong
 * Date: 2015/12/22
 * Time: 17:15
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\User;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link href="/adminx/css/animate.min.css" rel="stylesheet">
    <!--common scripts for all pages-->
    <link href="/adminx/css/style.css" rel="stylesheet">
    <link href="/adminx/css/style-responsive.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/adminx/js/html5shiv.js"></script>
    <script src="/adminx/js/respond.min.js"></script>
    <![endif]-->
    <!-- Placed js at the end of the document so the pages load faster -->
    <script src="/adminx/js/jquery-1.10.2.min.js"></script>
    <script src="/adminx/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="/adminx/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="/adminx/js/bootstrap.min.js"></script>
    <script src="/adminx/js/modernizr.min.js"></script>
    <script src="/adminx/js/jquery.nicescroll.js"></script>
    <script src="/tools/layer/layer.js"></script>
</head>

<body class="sticky-header">
<?php $this->beginBody() ?>
<section>
    <!-- left side start-->
    <div class="left-side sticky-left-side">

        <!--个人资料 start-->
        <div class="logo   dropdown">
            <img src="/adminx/images/user-avatar.png">

            <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="true">
                                <span class="clear">
                               <span class="block m-t-xs"><strong
                                       class="font-bold"><?= Yii::$app->getUser()->identity->attributes['username'] ?></strong></span>
                                    <span class="text-muted text-xs block">
                                        <?=User::findIdentity(Yii::$app->user->id)->rolenames; ?>
                                        <b class="caret"></b></span>
                                </span>
            </a>
            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                <li><a class="J_menuItem" href="form_avatar.html" data-index="0">个人资料</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="/index.php?r=site/logout" data-method="post"><i class="icon-off"></i>安全退出</a>
                </li>
            </ul>
        </div>

        <div class="logo-icon text-center"><a href="/"><i class="fa fa-home"></i></a></div>
        <!--个人资料  end-->


        <div class="left-side-inner">
            <!-- visible to small devices only -->
            <!--sidebar nav start-->
            <!--左边菜单-->
            <?= $this->render('/common/leftMenu') ?>
            <!--sidebar nav end-->

        </div>
    </div>
    <!-- left side end-->

    <!-- main content start-->
    <div class="main-content">

        <!-- header section start-->
        <div class="header-section">
            <!--toggle button start-->
            <a class="toggle-btn"><i class="fa fa-bars"></i></a>
            <!--toggle button end-->

            <!--notification menu start -->
            <!--快捷菜单-->
            <?= $this->render('/common/topMenu') ?>
            <!--notification menu end -->

        </div>
        <!-- header section end-->
        <!--面包屑-->
        <?= $this->render('_breadcrumbs') ?>
        <!--body wrapper start-->
        <div class="wrapper">
            <?= $content ?>
        </div>
        <!--body wrapper end-->

    </div>
    <!-- main content end-->
</section>



<script src="/adminx/js/scripts.js"></script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>